app.home.page=/#/home
back_instance_service_name = finalgithub-back
config_location=vb-eva-gen-configuration
custom_domain_name =
db_auth_file_json=sa-fs-connection-json
db_connection_info=db_connection_info
db_type=RDBMS
encrypted_secrets=false
files_auth_file_json=sa-fs-connection-json
google_oauth_info=google_oauth_info
key_id= 
key_location_id=europe-west1
key_ring_id=
local-env=false
lz-disabled=true
module_name=finalgithub
project_id=vb-eva-gen
project_location = europe-west1
rdbms_name=GOOGLE_CLOUD_SQL_MYSQL
store_writer_status_per_no_of_records=10
vault_provider=GoogleSecretVaultProvider

#IMPORT PROPERTIES
import.config.rappitimport.system.noofparallelUploads=1
import.config.rappitimport.system.bucketname=
export.config.rappitexport.system.bucketname=

admin_user_first_names=
admin_user_last_names=
admin_users=
spring.threads.virtual.enabled=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#OUTBOX PROPERTIES
outbox.bq.processing.mode=ASYNC
outbox.es.processing.mode=ASYNC
outbox.processing.enabled=true
outbox.startup.recovery.enabled=false
outbox.startup.recovery.delay-seconds=20

# SPRING PROPERTIES
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
supported_auth_providers=google

management.tracing.enabled=false
management.tracing.sampling.probability=1.0
spring.cloud.gcp.trace.enabled=false
tracing.enabled=false 
