# RD PROPERTIES 
anonymous-be-paths=/api-docs,/api-docs.yaml,/swagger-ui.html,/*/swagger-ui/*,/*/api-docs/*,/*/oauth2/authorization/google,/*/sso/*,/*/oauth2/code/google,/environmentinfo/info,/error,/rest/applicationusers/loadusers,/rest/deploy/setup,/rest/rdbms/generatesqlscript,/rest/login-providers/oauth-login-providers,/_ah/start,/rest/ping,/rest/oauth2/token,/rest/google-identity/authenticate,/rest/google-identity/firebase-config,/rest/multitenant/tenant-retrieve,/rest/auth-revoked-tokens/clear-expired
anonymous-fe-paths=/,/ngsw.json,/ngsw-worker.js,/manifest.webmanifest,/manifest.json,/signup.component.html,/landing-page-landing-page-module.js,/assets/*/*.png,/assets/*/*.json,/assets/*/*.svg,/assets/*/*.jpg,/index.html,/favicon.ico,/*.js,/*/*.js,/*/*.js.map,/*/*.css,/*.css,/*.png,/*.jpg,/*.jpeg,/*.gif,/*/*.png,/*/*.jpg,/*/*.jpeg,/*/*.gif,/*/*.ttf,/*/*.json,/*/*.woff,/*.woff2,/*.woff,/*/*.woff2,/*/*.eot,/*/*.svg,/*/svg,/*.css.map
memcached.cache.expiration=1d
memcached.cache.expiration-per-cache.Lock=300
memcached.cache.provider=static
memcached.cache.servers=@memcached-ip@
server.compression.enabled=true
server.compression.min-response-size=10240
server.compression.mime-types=application/javascript,application/json,text/html,text/xml,text/plain,text/css,application/xml,text/javascript
application.type=independent
all_domain_users_login=false
all_domain_users_mapped_appuser=
exception.response.camelcase=false
page.config.system.list.queryview.showtotalcount=true
page.config.system.list.standardpages.showtotalcount=true

# SPRING PROPERTIES
logging.pattern.console=%highlight(%d{HH:mm:ss.SSS} %-5level [%X{userSid:-Application},%X{traceId:-},%X{spanId:-}] [%thread]) %logger{36} - %msg%n
logging.level.org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator=WARN
logging.level.org.hibernate.orm.connections.pooling=WARN
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
server.http2.enabled=true
server.port=9090
server.undertow.max-http-post-size=32MB
spring.config.import=optional:classpath:application.properties,optional:classpath:application-@spring.profiles.active@-base.properties
spring.main.lazy-initialization=true
spring.profiles.active=@spring.profiles.active@
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=32MB
spring.servlet.multipart.max-request-size=32MB
spring.session.store-type=none
springdoc.api-docs.path=/api-docs

# JPA PROPERTIES
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=0
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.jpa.properties.hibernate.jdbc.fetch_size=50

